export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_BREEDS_PENDING = 'REQUEST_BREEDS_PENDING';
export const REQUEST_BREEDS_SUCCESS = 'REQUEST_BREEDS_SUCCESS';
export const REQUEST_BREEDS_FULL_SUCCESS = 'REQUEST_BREEDS_FULL_SUCCESS';
export const REQUEST_BREEDS_FAILED = 'REQUEST_BREEDS_FAILED';